import mongoose from 'mongoose';
import ParentBlog from '../models/ParentBlog';
import ChildBlog from '../models/ChildBlog';
import { NotFoundError, AuthorizationError, ValidationError } from '../utils/errors';

export class ParentBlogService {
  static async getAll(publishedOnly = true) {
    const query: any = {};
    if (publishedOnly) {
      query.isPublished = true;
    }

    return await ParentBlog.find(query)
      .populate('authorId', 'username profileImage')
      .populate({
        path: 'children',
        match: { isPublished: true },
        options: { sort: { publishedAt: -1 }, limit: 5 },
        populate: {
          path: 'authorId',
          select: 'username profileImage'
        }
      })
      .populate('tags', 'name slug color')
      .sort({ order: 1, createdAt: -1 });
  }

  static async getBySlug(slug: string) {
    const parentBlog = await ParentBlog.findOne({ slug, isPublished: true })
      .populate('authorId', 'username profileImage bio')
      .populate({
        path: 'children',
        match: { isPublished: true },
        options: { sort: { publishedAt: -1 } },
        populate: [
          {
            path: 'authorId',
            select: 'username profileImage'
          },
          {
            path: 'tags',
            select: 'name slug color'
          }
        ]
      })
      .populate('tags', 'name slug color');

    if (!parentBlog) {
      throw new NotFoundError('Parent blog not found');
    }

    return parentBlog;
  }

  static async create(authorId: string, data: any) {
    const { title, description, imageUrl, order, isPublished, metaTitle, metaDescription, tags } = data;

    // Slug is automatically generated by mongoose schema pre('save') but we can also set it explicitly
    const slug = title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)/g, '');

    const parentBlog = await ParentBlog.create({
      title,
      slug,
      description,
      imageUrl,
      order: order || 0,
      isPublished: isPublished || false,
      metaTitle,
      metaDescription,
      authorId: new mongoose.Types.ObjectId(authorId),
      tags: tags || []
    });

    return await ParentBlog.findById(parentBlog._id)
      .populate('authorId', 'username profileImage')
      .populate('tags', 'name slug color');
  }

  static async update(id: string, userId: string, userRole: string, data: any) {
    const parentBlog = await ParentBlog.findById(id);
    if (!parentBlog) {
      throw new NotFoundError('Parent blog not found');
    }

    // Check ownership/permissions
    if (parentBlog.authorId.toString() !== userId && userRole !== 'admin') {
      throw new AuthorizationError('Not authorized to update this blog');
    }

    const { title, description, imageUrl, order, isPublished, metaTitle, metaDescription, tags } = data;

    if (title && title !== parentBlog.title) {
      parentBlog.title = title;
      parentBlog.slug = title
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/(^-|-$)/g, '');
    }

    if (description !== undefined) parentBlog.description = description;
    if (imageUrl !== undefined) parentBlog.imageUrl = imageUrl;
    if (order !== undefined) parentBlog.order = order;
    if (isPublished !== undefined) parentBlog.isPublished = isPublished;
    if (metaTitle !== undefined) parentBlog.metaTitle = metaTitle;
    if (metaDescription !== undefined) parentBlog.metaDescription = metaDescription;
    if (tags !== undefined) parentBlog.tags = tags;

    await parentBlog.save();

    return await ParentBlog.findById(id)
      .populate('authorId', 'username profileImage')
      .populate('tags', 'name slug color');
  }

  static async delete(id: string, userId: string, userRole: string) {
    const parentBlog = await ParentBlog.findById(id);
    if (!parentBlog) {
      throw new NotFoundError('Parent blog not found');
    }

    if (parentBlog.authorId.toString() !== userId && userRole !== 'admin') {
      throw new AuthorizationError('Not authorized to delete this blog');
    }

    // Prevent deletion if child blogs exist
    const childBlogsCount = await ChildBlog.countDocuments({ parentId: id });
    if (childBlogsCount > 0) {
      throw new ValidationError('Cannot delete parent blog with child blogs. Delete child blogs first.');
    }

    await ParentBlog.deleteOne({ _id: id });
  }

  static async getAdminList(page: number, limit: number, search: string) {
    const skip = (page - 1) * limit;

    const filter: any = {};
    if (search) {
      filter.title = { $regex: search, $options: 'i' };
    }

    const [parentBlogs, total] = await Promise.all([
      ParentBlog.find(filter)
        .populate('authorId', 'username')
        .sort({ createdAt: -1 })
        .skip(skip)
        .limit(limit),
      ParentBlog.countDocuments(filter)
    ]);

    return {
      parentBlogs,
      pagination: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit)
      }
    };
  }
}
